CASTSEQUENCE_ID -> "/castsequence" {% data => ({ type: "command", data}) %}

CASTSEQUENCE_OPTION -> SPELL
CASTSEQUENCE_OPTION_LIST -> SPELL | CASTRANDOM_OPTION_LIST COMMA SPELL
CASTSEQUENCE_MOD_OPTION -> "target" | "focus" | NUMBER
CASTSEQUENCE_MOD_OPTION_LIST -> CASTSEQUENCE_MOD_OPTION | CASTSEQUENCE_MOD_OPTION "/" CASTSEQUENCE_MOD_OPTION
CASTSEQUENCE_MOD -> _ "reset=" CASTSEQUENCE_MOD_OPTION_LIST

CASTSEQUENCE_LINE -> CASTSEQUENCE_ID CASTSEQUENCE_MOD:? _ CASTSEQUENCE_OPTION_LIST
