EQUIP_SIMPLE_ID -> "/equip"
EQUIP_SIMPLE_LINE -> EQUIP_SIMPLE_ID _ SPELL

EQUIPSLOT_ID -> "/equipslot"
EQUIPSLOT_ITEM -> SPELL | "item:" NUMBER ":" NUMBER
EQUIPSLOT_LINE -> EQUIPSLOT_ID _ NUMBER _ EQUIPSLOT_ITEM

EQUIP_LINE -> EQUIP_SIMPLE_LINE | EQUIPSLOT_LINE
