SETTINGS_CONSOLE_ID -> "/console"
SETTINGS_CONSOLE_VALUE -> NUMBER | NUMBER_DECIMAL
SETTINGS_CONSOLE_LINE -> SETTINGS_CONSOLE_ID _ TEXT _ SETTINGS_CONSOLE_VALUE

SETTINGS_SCRIPT_ID -> "/script"
SETTINGS_SCRIPT_SETCVAR -> "SetCVar"
SETTINGS_SCRIPT_VALUE -> NUMBER | NUMBER_DECIMAL

SETTINGS_SCRIPT_LINE -> TARGET_SCRIPT_ID _ SETTINGS_SCRIPT_SETCVAR "(\"" TEXT "\"" COMMA SETTINGS_SCRIPT_VALUE ")"

SETTINGS_LINE -> SETTINGS_CONSOLE_LINE | SETTINGS_SCRIPT_LINE
