# TODO
SHOWTOOLTIP_ID -> "#showtooltip" {% d=> ({ type: 'showtooltip', data: d.join('')}) %}

SHOWTOOLTIP_ITEM -> MOD:? _:? SPELL {% d=> d.length >1 ? [d[0], d[2]] : d.pop() %}
SHOWTOOLTIP_LIST -> SHOWTOOLTIP_ITEM | SHOWTOOLTIP_ITEM SEMICOLON | SHOWTOOLTIP_LIST SEMICOLON SHOWTOOLTIP_ITEM

SHOWTOOLTIP_LINE -> SHOWTOOLTIP_ID | SHOWTOOLTIP_ID SHOWTOOLTIP_LIST
