# TODO
SHOWTOOLTIP_ID -> "#showtooltip"

SHOWTOOLTIP_ITEM -> MOD:? _:? SPELL
SHOWTOOLTIP_LIST -> SHOWTOOLTIP_ITEM | SHOWTOOLTIP_ITEM SEMICOLON | SHOWTOOLTIP_LIST SEMICOLON SHOWTOOLTIP_ITEM

SHOWTOOLTIP_LINE -> SHOWTOOLTIP_ID | SHOWTOOLTIP_ID SHOWTOOLTIP_LIST
