USE_ID -> "/use"

USE_EQUIPPED -> MOD:? _:? NUMBER
USE_GEAR -> MOD:? _:? SPELL
USE_ITEM -> USE_EQUIPPED | USE_GEAR
USE_ITEM_LIST -> USE_ITEM | USE_ITEM SEMICOLON | USE_ITEM_LIST SEMICOLON USE_ITEM

USE_LINE -> USE_ID USE_ITEM_LIST
